name: Validate Renovate Configuration

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/validate-renovatecfg.yaml"
      - ".github/renovate.json"
  workflow_dispatch: {}

jobs:
  check:
    name: Check if there is a new upstream release
    runs-on: ubuntu-latest
    steps:
      - name: Validate Renovate Configuration with renovate-config-validator
        uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.0.1
